// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0LQ7fkLKP4x9RGfBOWA1yKZJI6wpMvUg',
    appId: '1:553841081847:web:b46286a2390df3efda02f2',
    messagingSenderId: '553841081847',
    projectId: 'mynotes-flutter-project-100',
    authDomain: 'mynotes-flutter-project-100.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqaJCWV7-IrLjZsH1-DbfL6b1kp7tY8k',
    appId: '1:553841081847:android:59ae2b64ad78821dda02f2',
    messagingSenderId: '553841081847',
    projectId: 'mynotes-flutter-project-100',
    storageBucket: 'mynotes-flutter-project-100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkv5tgq7MsDOZYN7nKCWVs-dqVlbmUfo',
    appId: '1:553841081847:ios:34ad89a7f1dea9adda02f2',
    messagingSenderId: '553841081847',
    projectId: 'mynotes-flutter-project-100',
    storageBucket: 'mynotes-flutter-project-100.appspot.com',
    iosClientId: '553841081847-hp9faltquqdu7jnjotive08m00jjrc8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
